<?php
require_once("../secret.php");
//Get the platform and format it 
$plattform = htmlspecialchars($_GET['p']);
$plattform = strtolower($plattform);
//Check for valid platforms
if($plattform != "pc" && $plattform != "xbox" && $plattform != "ps4"){
    //redirect to error page
    echo "Error: Invalid Platform";
    exit;
}

$playerName = htmlspecialchars($_GET['n']);
//This could be verified, but I do not think its actually exploitable
/*
    The verification would need to be able to work for xbox. ps4 and pc name restrictions
*/

echo "Player: {$playerName} on {$plattform} <br>";

// $p Platform
// $n Player Name

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$curl_name = rawurlencode($playerName);
echo "Encoded Name: {$curl_name} <br>";
$curl_plat = rawurlencode($plattform);

curl_setopt($ch, CURLOPT_URL, "{$s_url1}{$curl_plat}{$s_url2}{$curl_name}{$s_url3}");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = $s_header;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo $result;

//We no longer need these here
unset($s_header);
unset($s_url1);
unset($s_url2);
unset($s_url3);

?>