<?php

$plattform = preg_replace('/[^A-Za-z0-9]+/', "", $p);
$plattform = strtolower($plattform);

if($plattform != "pc" && $plattform != "xbox" && $plattform != "ps4"){
    //redirect to error page
    echo "Error: Invalid Platform";
    exit;
}

// $p Platform
// $n Player Name

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, '');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'X-Api-Key: sadasdadasdasdas';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

?>